insert into projects values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'DIABETICS CONTROL', 'Gumenchuk','Kiev');
insert into projects values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'CARGO DISTANCE', 'Kunin','Vien');
insert into projects values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'CRM COMMERCE', 'Kovalenko','Lviv');
insert into projects values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'CHAT PROJECT', 'Pavlenko','Kharkiv');
insert into projects values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NEIROSYSTEM', 'Pavlenko','Kharkiv');
insert into employees values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Igor', 'Kostenko','Male', 32,'kost23@gmail.com', 'developer');
insert into employees values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Anna', 'Shmatko','Female', 29,'anna.smith@gmail.com', 'analyst');
insert into employees values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'John', 'Brown','Male', 33,'john.brown@ukr.net', 'engineer');
insert into employees values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Mary', 'Sumko','Female', 27,'mary.sumko@gmail.com', 'tester');
insert into employees values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Jan', 'Grynko','Male', 36,'jan.grson@ukr.net', 'consultant');
insert into employees values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Emma', 'Davydova','Female', 30,'emma.dav@gmail.com', 'writer');
insert into employees values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'David', 'Miller','Male', 34,'david.miller@ukr.net', 'developer');
insert into employees values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Sophia', 'Tayfun','Female', 32,'sophia.tay@gmail.com', 'editor');
insert into employees values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Michael', 'Chuiko','Male', 37,'michael.chuiko@ukr.net', 'salesman');
insert into employees values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Emily', 'Moore','Female', 28,'emily.moore@gmail.com', 'analyst');
insert into employees values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Daniel', 'Levko','Male', 31,'daniel.lev@ukr.net', 'designer');
insert into employees values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Olivia', 'White','Female', 26,'olivia.white@gmail.com', 'architect');
insert into employees values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Vlad', 'Kustov','Male', 35,'vlad.kustov@ukr.net', 'developer');
insert into employees values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Isabella', 'Topenko','Female', 33,'isabella.thompson@gmail.com', 'designer');
insert into employees values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Alexander', 'Danko','Male', 38,'alexander.danko@ukr.net', 'architect');
insert into employees values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Abigail', 'Young','Male', 29,'abigail.young@gmail.com', 'tester');
insert into employees values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Jacob', 'King','Male', 32,'jacob.king@ukr.net', 'chef');
insert into employees values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Andrey', 'Varavin','Male', 30,'andrey.varavin@gmail.com', 'analyst');
insert into employees values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Edward', 'Gvozdev','Male', 34,'edward.gvod@ukr.net', 'developer');
insert into employees values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Sergey', 'Vinnik','Male', 31,'serg.vinnik@gmail.com', 'engineer');
insert into employees values (21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Alex', 'Sidorenko','Male', 36,'alex.sid@ukr.net', 'chef');

insert into project_emp values (1, 1);
insert into project_emp values (1, 2);
insert into project_emp values (1, 3);
insert into project_emp values (1, 4);
insert into project_emp values (1, 5);
insert into project_emp values (2, 6);
insert into project_emp values (2, 7);
insert into project_emp values (2, 8);
insert into project_emp values (2, 9);
insert into project_emp values (2, 10);
insert into project_emp values (3, 11);
insert into project_emp values (3, 12);
insert into project_emp values (3, 13);
insert into project_emp values (3, 14);
insert into project_emp values (3, 15);
insert into project_emp values (4, 16);
insert into project_emp values (4, 17);
insert into project_emp values (4, 18);
insert into project_emp values (4, 19);
insert into project_emp values (4, 20);
insert into project_emp values (5, 6);
insert into project_emp values (5, 7);
insert into project_emp values (5, 8);
insert into project_emp values (5, 9);
insert into project_emp values (5, 10);
insert into project_emp values (1, 11);
insert into project_emp values (1, 20);
insert into project_emp values (1, 21);
